services:
  intranet:
    build:
      context: ./intranet
      dockerfile: Dockerfile
    image: intranet
    container_name: intranet
    networks:
      - asa-network
  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    image: portal
    container_name: portal
    networks:
      - asa-network
  webmail:
    build:
      context: ./webmail
      dockerfile: Dockerfile
    image: webmail
    container_name: webmail
    networks:
      - asa-network
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    container_name: proxy
    ports:
      - "8080:80"
    depends_on:
      - intranet
      - portal
      - webmail
    networks:
      - asa-network
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    image: dns
    container_name: dns
    hostname: ns1.asa.br
    restart: always
    tty: true
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - asa-network
#Docker Networks
networks:
  asa-network:
    driver: bridge